---
- name: Install and start httpd
  hosts: 192.168.0.40
  become: yes
  tasks:
    - name: Install htppd
      yum:
        name: httpd
        state: present
    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
