---
- name: Update all packages to the latest version
  hosts: webservers
  become: yes # wykonaj zadanie z uprawnieniami administratora(root)
  tasks:
    - name: Update all packages
      yum:  # jest to moduł, który pozwala na zarzadzanie pakeitami
        name: "*" # wszystkie pakiety
        state: latest # aktualizacja do najnowszej wersji
        update_cache: yes # odświeżenie cache
